[package]
name = "error-window"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error-window-macro = {path = "./error-window-macro"}
dialog = "0.3.0"
